version: '3.8'

services:
  # O BANCO DE DADOS
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password_seguro_123 # Mude isso
      POSTGRES_DB: imobiliaria
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Opcional: feche isso em produção no firewall AWS

  # A SUA API NESTJS
  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password_seguro_123@postgres:5432/imobiliaria?schema=public"
      PORT: 3000
      # Configuração para o Puppeteer no Docker
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome-stable"
    volumes:
      # Persiste as imagens enviadas mesmo se reiniciar o container
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - postgres

volumes:
  postgres_data: